language: dart
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - cd packages/debug_bricks_core/
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache