name: example
description: Debug brick Easy Localization example

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  easy_localization: 3.0.1
  debug_bricks_core:
    path: ../../debug_bricks_core
  debug_bricks_ui:
    path: ../../debug_bricks_ui
  debug_bricks_easy_localization:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
