name: Test

on:
  push:
    branches: ['*']

  pull_request:
    branches: ['*']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev' # or: 'dev' or 'beta'

    - name: Actions for debug_bricks_core
      run: cd packages/debug_bricks_core/

    - name: Install packages dependencies
      run: flutter pub get

    - name: Analyze the project's Dart code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Run tests coverage
      run: flutter test --coverage